import 'package:flutter/material.dart';

/// Model representing a Task audit history log entry with rich actor and event metadata.
class TaskHistory {
  final String id;
  final String? taskId;
  final String? taskTitle;
  final String action;
  final String? oldValue;
  final String? newValue;
  final String? reason;
  final String? createdByUserId;
  final String? actorName;
  final String? actorEmail;
  final DateTime createdAt;

  const TaskHistory({
    required this.id,
    this.taskId,
    this.taskTitle,
    required this.action,
    this.oldValue,
    this.newValue,
    this.reason,
    this.createdByUserId,
    this.actorName,
    this.actorEmail,
    required this.createdAt,
  });

  factory TaskHistory.fromJson(Map<String, dynamic> json) {
    return TaskHistory(
      id: json['id'] as String,
      taskId: json['task_id'] as String?,
      taskTitle: json['task_title'] as String?,
      action: json['action'] as String,
      oldValue: json['old_value'] as String?,
      newValue: json['new_value'] as String?,
      reason: json['reason'] as String?,
      createdByUserId: json['created_by_user_id'] as String?,
      actorName: json['actor_name'] as String?,
      actorEmail: json['actor_email'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
    );
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'task_id': taskId,
        'task_title': taskTitle,
        'action': action,
        'old_value': oldValue,
        'new_value': newValue,
        'reason': reason,
        'created_by_user_id': createdByUserId,
        'actor_name': actorName,
        'actor_email': actorEmail,
        'created_at': createdAt.toIso8601String(),
      };

  /// Safe display name for the actor who performed this action.
  String get displayActor {
    if (actorName != null && actorName!.isNotEmpty) {
      return actorName!;
    }
    if (createdByUserId != null) {
      return 'Former user';
    }
    return 'System';
  }

  /// Categorical grouping for filtering and styling.
  String get actionCategory {
    switch (action.toLowerCase()) {
      case 'created':
      case 'created_from_template':
      case 'generated_from_recurrence':
        return 'creation';
      case 'status_changed':
      case 'completed':
      case 'reopened':
        return 'status';
      case 'priority_changed':
        return 'priority';
      case 'reassigned':
        return 'assignment';
      case 'attempt':
      case 'attempt_override':
        return 'attempt';
      case 'postponed':
      case 'next_action_date_changed':
      case 'reminder_created':
      case 'follow_up_created':
      case 'follow_up_completed':
        return 'scheduling';
      default:
        return 'general';
    }
  }

  /// Human-readable title describing the action.
  String get formattedAction {
    switch (action.toLowerCase()) {
      case 'created':
        return 'Task created';
      case 'created_from_template':
        return 'Created from template';
      case 'generated_from_recurrence':
        return 'Generated by recurrence schedule';
      case 'status_changed':
        final toVal = _formatStatusOrPriority(newValue);
        final fromVal = _formatStatusOrPriority(oldValue);
        if (fromVal.isNotEmpty && toVal.isNotEmpty) {
          return 'Status changed: $fromVal → $toVal';
        }
        return 'Status changed to ${toVal.isNotEmpty ? toVal : (newValue ?? "")}';
      case 'priority_changed':
        final toVal = _formatStatusOrPriority(newValue);
        final fromVal = _formatStatusOrPriority(oldValue);
        if (fromVal.isNotEmpty && toVal.isNotEmpty) {
          return 'Priority changed: $fromVal → $toVal';
        }
        return 'Priority changed to ${toVal.isNotEmpty ? toVal : (newValue ?? "")}';
      case 'reassigned':
        if (oldValue == null || oldValue == 'None' || oldValue!.isEmpty) {
          return 'Task assigned';
        }
        if (newValue == null || newValue == 'None' || newValue!.isEmpty) {
          return 'Task unassigned';
        }
        return 'Task reassigned';
      case 'attempt':
        return 'Work attempt ${newValue ?? "1"} recorded';
      case 'attempt_override':
        return 'Override attempt ${newValue ?? "1"} recorded';
      case 'postponed':
        final formattedDate = _formatIsoDate(newValue);
        return 'Task postponed to $formattedDate';
      case 'next_action_date_changed':
        final formattedDate = _formatIsoDate(newValue);
        return 'Next action date set to $formattedDate';
      case 'completed':
        return 'Task marked as completed';
      case 'reopened':
        return 'Task reopened';
      case 'subject_line_changed':
        return 'Subject line updated';
      case 'reminder_created':
        return 'Reminder scheduled';
      case 'follow_up_created':
        return 'Follow-up action scheduled';
      case 'follow_up_completed':
        return 'Follow-up marked as completed';
      default:
        return action.replaceAll('_', ' ').split(' ').map((w) {
          if (w.isEmpty) return '';
          return w[0].toUpperCase() + w.substring(1).toLowerCase();
        }).join(' ');
    }
  }

  /// Icon representing the action.
  IconData get actionIcon {
    switch (action.toLowerCase()) {
      case 'created':
        return Icons.add_circle_outline;
      case 'created_from_template':
        return Icons.copy_outlined;
      case 'generated_from_recurrence':
        return Icons.autorenew;
      case 'status_changed':
        return Icons.sync_alt;
      case 'priority_changed':
        return Icons.flag_outlined;
      case 'reassigned':
        return Icons.person_outline;
      case 'attempt':
        return Icons.work_history_outlined;
      case 'attempt_override':
        return Icons.warning_amber_rounded;
      case 'postponed':
        return Icons.update;
      case 'next_action_date_changed':
        return Icons.schedule_send;
      case 'completed':
        return Icons.check_circle_outline;
      case 'reopened':
        return Icons.replay;
      case 'subject_line_changed':
        return Icons.subject;
      case 'reminder_created':
        return Icons.notifications_active_outlined;
      case 'follow_up_created':
      case 'follow_up_completed':
        return Icons.call_made_outlined;
      default:
        return Icons.history;
    }
  }

  IconData get categoryIcon => actionIcon;

  /// Theme accent color for the action.
  Color get actionColor {
    switch (action.toLowerCase()) {
      case 'created':
      case 'created_from_template':
      case 'generated_from_recurrence':
        return Colors.teal;
      case 'completed':
        return Colors.green;
      case 'reopened':
        return Colors.purple;
      case 'priority_changed':
        return Colors.deepOrange;
      case 'status_changed':
        return Colors.blue;
      case 'reassigned':
        return Colors.indigo;
      case 'attempt':
        return Colors.amber.shade800;
      case 'attempt_override':
        return Colors.red.shade700;
      case 'postponed':
        return Colors.orange.shade800;
      case 'next_action_date_changed':
        return Colors.cyan.shade700;
      case 'reminder_created':
      case 'follow_up_created':
      case 'follow_up_completed':
        return Colors.blueGrey;
      default:
        return Colors.grey.shade700;
    }
  }

  Color get categoryColor => actionColor;

  /// Whether oldValue and newValue represent a human-visible change.
  bool get hasDiff {
    if (action == 'created' || action == 'created_from_template' || action == 'generated_from_recurrence') {
      return false;
    }
    return (oldValue != null && oldValue!.isNotEmpty) || (newValue != null && newValue!.isNotEmpty);
  }

  /// Formatted old value string for diff display.
  String get formattedOldValue => _formatDiffValue(oldValue);

  /// Formatted new value string for diff display.
  String get formattedNewValue => _formatDiffValue(newValue);

  static String _formatStatusOrPriority(String? val) {
    if (val == null || val.isEmpty || val == 'None') return '';
    return val.replaceAll('_', ' ').toUpperCase();
  }

  static String _formatDiffValue(String? val) {
    if (val == null || val.isEmpty || val == 'None') return 'none';
    if (val.contains('T') && val.contains('-') && (val.endsWith('Z') || val.contains('+') || val.length >= 19)) {
      try {
        final dt = DateTime.parse(val).toLocal();
        return '${dt.day}/${dt.month}/${dt.year} ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}';
      } catch (_) {}
    }
    return val;
  }

  static String _formatIsoDate(String? val) {
    if (val == null || val.isEmpty || val == 'None') return 'unspecified';
    try {
      final dt = DateTime.parse(val).toLocal();
      return '${dt.day}/${dt.month}/${dt.year}';
    } catch (_) {
      return val;
    }
  }
}

/// Paginated response of task history activity logs.
class TaskHistoryListResponse {
  final List<TaskHistory> items;
  final int total;
  final int page;
  final int pageSize;

  const TaskHistoryListResponse({
    required this.items,
    required this.total,
    required this.page,
    required this.pageSize,
  });

  factory TaskHistoryListResponse.fromJson(Map<String, dynamic> json) {
    final list = json['items'] as List<dynamic>? ?? [];
    return TaskHistoryListResponse(
      items: list.map((e) => TaskHistory.fromJson(e as Map<String, dynamic>)).toList(),
      total: json['total'] as int? ?? list.length,
      page: json['page'] as int? ?? 1,
      pageSize: json['page_size'] as int? ?? 20,
    );
  }
}
