"""Pydantic schemas and DTOs package for NextAction."""

from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    UserCreate,
    UserListResponse,
    UserResponse,
)
from app.schemas.client import (
    ClientCreate,
    ClientListResponse,
    ClientResponse,
    ClientUpdate,
)
from app.schemas.common import ErrorResponse, HealthResponse, PaginatedResponse, ReadinessResponse
from app.schemas.follow_up import (
    FollowUpCompleteRequest,
    FollowUpCreate,
    FollowUpResponse,
)
from app.schemas.history import TaskHistoryListResponse, TaskHistoryResponse
from app.schemas.notification import (
    NotificationEvaluateResponse,
    NotificationListResponse,
    NotificationResponse,
    UnreadCountResponse,
)
from app.schemas.recurring_task import (
    RecurringTaskCreate,
    RecurringTaskEvaluationRequest,
    RecurringTaskEvaluationResponse,
    RecurringTaskListResponse,
    RecurringTaskResponse,
    RecurringTaskUpdate,
)
from app.schemas.reminder import ReminderCreate, ReminderResponse
from app.schemas.task import (
    AssignmentChangeRequest,
    AttemptRequest,
    CompleteTaskRequest,
    NextActionDateRequest,
    OverrideAttemptRequest,
    PostponeTaskRequest,
    PriorityChangeRequest,
    ReopenTaskRequest,
    StatusChangeRequest,
    SubjectLineChangeRequest,
    TaskCreate,
    TaskListResponse,
    TaskResponse,
    TaskUpdate,
)
from app.schemas.task_template import (
    CreateTaskFromTemplateRequest,
    TaskTemplateCreate,
    TaskTemplateListResponse,
    TaskTemplateResponse,
    TaskTemplateUpdate,
)
from app.schemas.dashboard import (
    AssigneeWorkloadItem,
    ClientWorkloadItem,
    DashboardAttentionSummary,
    DashboardAttemptPressure,
    DashboardKpis,
    DashboardPriorityDistribution,
    DashboardSchedulingAnalytics,
    DashboardStatusDistribution,
    DashboardSummaryResponse,
    DashboardTimeRange,
    DashboardTrendPoint,
    DashboardWorkloadBreakdown,
    FollowUpAnalytics,
    ReminderAnalytics,
    WorkflowWorkloadItem,
)
from app.schemas.reports import (
    ActivityReportItem,
    ActivityReportResponse,
    ExportFormat,
    FollowUpReportItem,
    ProductivityDailyTrendPoint,
    ProductivityReportResponse,
    ReminderFollowUpReportResponse,
    ReminderFollowUpSummary,
    ReminderReportItem,
    ReportFilterParams,
    ReportType,
    TaskDetailReportItem,
    TaskDetailReportResponse,
    TaskSummaryPriorityBreakdown,
    TaskSummaryReport,
    TaskSummaryStatusBreakdown,
    WorkloadReportItem,
    WorkloadReportResponse,
)
from app.schemas.settings import (
    UserSettingsResponse,
    UserSettingsUpdate,
)
from app.schemas.scheduler import (
    CategoryEvaluationDetail,
    SchedulerEvaluationRequest,
    SchedulerEvaluationResponse,
)
from app.schemas.workflow import (
    WorkflowCreate,
    WorkflowListResponse,
    WorkflowResponse,
    WorkflowUpdate,
)

__all__ = [
    "HealthResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "UserCreate",
    "UserResponse",
    "LoginRequest",
    "TokenResponse",
    "ClientCreate",
    "ClientUpdate",
    "ClientResponse",
    "ClientListResponse",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowListResponse",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "AttemptRequest",
    "OverrideAttemptRequest",
    "PostponeTaskRequest",
    "NextActionDateRequest",
    "CompleteTaskRequest",
    "ReopenTaskRequest",
    "StatusChangeRequest",
    "PriorityChangeRequest",
    "AssignmentChangeRequest",
    "SubjectLineChangeRequest",
    "TaskHistoryResponse",
    "TaskHistoryListResponse",
    "ReminderCreate",
    "ReminderResponse",
    "FollowUpCreate",
    "FollowUpCompleteRequest",
    "FollowUpResponse",
    "NotificationResponse",
    "NotificationListResponse",
    "UnreadCountResponse",
    "NotificationEvaluateResponse",
    "TaskTemplateCreate",
    "TaskTemplateUpdate",
    "TaskTemplateResponse",
    "TaskTemplateListResponse",
    "CreateTaskFromTemplateRequest",
    "RecurringTaskCreate",
    "RecurringTaskUpdate",
    "RecurringTaskResponse",
    "RecurringTaskListResponse",
    "RecurringTaskEvaluationRequest",
    "RecurringTaskEvaluationResponse",
    "ExportFormat",
    "ReportType",
    "ReportFilterParams",
    "TaskSummaryStatusBreakdown",
    "TaskSummaryPriorityBreakdown",
    "TaskSummaryReport",
    "TaskDetailReportItem",
    "TaskDetailReportResponse",
    "ProductivityDailyTrendPoint",
    "ProductivityReportResponse",
    "WorkloadReportItem",
    "WorkloadReportResponse",
    "ActivityReportItem",
    "ActivityReportResponse",
    "ReminderFollowUpSummary",
    "ReminderReportItem",
    "FollowUpReportItem",
    "ReminderFollowUpReportResponse",
    "UserSettingsResponse",
    "UserSettingsUpdate",
    "CategoryEvaluationDetail",
    "SchedulerEvaluationRequest",
    "SchedulerEvaluationResponse",
]

