import 'package:flutter_test/flutter_test.dart';
import 'package:nextaction/models/history/task_history_models.dart';

void main() {
  group('Phase 15: TaskHistory Model and Formatting Tests', () {
    test('TaskHistory parses JSON accurately with enriched fields', () {
      final json = {
        'id': 'hist-1',
        'task_id': 'task-100',
        'task_title': 'Quarterly Financial Review',
        'action': 'priority_changed',
        'old_value': 'medium',
        'new_value': 'high',
        'reason': 'Escalated by management',
        'created_by_user_id': 'user-1',
        'actor_name': 'Bhanu Pratap',
        'actor_email': 'bhanu@example.com',
        'created_at': '2026-09-28T10:30:00Z',
      };

      final history = TaskHistory.fromJson(json);

      expect(history.id, equals('hist-1'));
      expect(history.taskId, equals('task-100'));
      expect(history.taskTitle, equals('Quarterly Financial Review'));
      expect(history.action, equals('priority_changed'));
      expect(history.oldValue, equals('medium'));
      expect(history.newValue, equals('high'));
      expect(history.reason, equals('Escalated by management'));
      expect(history.createdByUserId, equals('user-1'));
      expect(history.actorName, equals('Bhanu Pratap'));
      expect(history.actorEmail, equals('bhanu@example.com'));
      expect(history.displayActor, equals('Bhanu Pratap'));
      expect(history.actionCategory, equals('priority'));
      expect(history.formattedAction, equals('Priority changed: MEDIUM → HIGH'));
      expect(history.hasDiff, isTrue);
      expect(history.formattedOldValue, equals('medium'));
      expect(history.formattedNewValue, equals('high'));
    });

    test('Actor fallback resolves correctly for former and system users', () {
      // 1. Deleted/Former user (actor_name is null, but createdByUserId is present)
      final formerHistory = TaskHistory(
        id: 'hist-former',
        action: 'status_changed',
        createdByUserId: 'deleted-user-uuid',
        actorName: null,
        createdAt: DateTime.now(),
      );
      expect(formerHistory.displayActor, equals('Former user'));

      // 2. System / Automated action (both actor_name and createdByUserId are null)
      final systemHistory = TaskHistory(
        id: 'hist-system',
        action: 'generated_from_recurrence',
        createdByUserId: null,
        actorName: null,
        createdAt: DateTime.now(),
      );
      expect(systemHistory.displayActor, equals('System'));

      // 3. Explicit actor name
      final regularHistory = TaskHistory(
        id: 'hist-regular',
        action: 'created',
        createdByUserId: 'user-2',
        actorName: 'Alice Smith',
        createdAt: DateTime.now(),
      );
      expect(regularHistory.displayActor, equals('Alice Smith'));
    });

    test('Human readable action formatting covers taxonomy', () {
      final baseDate = DateTime(2026, 9, 29, 10, 0);

      // Creation & automation
      expect(
        TaskHistory(id: '1', action: 'created', createdAt: baseDate).formattedAction,
        equals('Task created'),
      );
      expect(
        TaskHistory(id: '2', action: 'created_from_template', createdAt: baseDate).formattedAction,
        equals('Created from template'),
      );
      expect(
        TaskHistory(id: '3', action: 'generated_from_recurrence', createdAt: baseDate).formattedAction,
        equals('Generated by recurrence schedule'),
      );

      // Status changes & completion
      expect(
        TaskHistory(id: '4', action: 'status_changed', oldValue: 'pending', newValue: 'in_progress', createdAt: baseDate).formattedAction,
        equals('Status changed: PENDING → IN PROGRESS'),
      );
      expect(
        TaskHistory(id: '5', action: 'completed', createdAt: baseDate).formattedAction,
        equals('Task marked as completed'),
      );
      expect(
        TaskHistory(id: '6', action: 'reopened', createdAt: baseDate).formattedAction,
        equals('Task reopened'),
      );

      // Assignments
      expect(
        TaskHistory(id: '7', action: 'reassigned', oldValue: null, newValue: 'user-1', createdAt: baseDate).formattedAction,
        equals('Task assigned'),
      );
      expect(
        TaskHistory(id: '8', action: 'reassigned', oldValue: 'user-1', newValue: 'None', createdAt: baseDate).formattedAction,
        equals('Task unassigned'),
      );
      expect(
        TaskHistory(id: '9', action: 'reassigned', oldValue: 'user-1', newValue: 'user-2', createdAt: baseDate).formattedAction,
        equals('Task reassigned'),
      );

      // Attempts & scheduling
      expect(
        TaskHistory(id: '10', action: 'attempt', newValue: '2 of 3', createdAt: baseDate).formattedAction,
        equals('Work attempt 2 of 3 recorded'),
      );
      expect(
        TaskHistory(id: '11', action: 'attempt_override', newValue: '4 of 3', createdAt: baseDate).formattedAction,
        equals('Override attempt 4 of 3 recorded'),
      );
      expect(
        TaskHistory(id: '12', action: 'postponed', newValue: '2026-10-15T00:00:00Z', createdAt: baseDate).formattedAction,
        contains('Task postponed to'),
      );
      expect(
        TaskHistory(id: '13', action: 'next_action_date_changed', newValue: '2026-10-01T09:00:00Z', createdAt: baseDate).formattedAction,
        contains('Next action date set to'),
      );
      expect(
        TaskHistory(id: '14', action: 'subject_line_changed', createdAt: baseDate).formattedAction,
        equals('Subject line updated'),
      );
    });

    test('Action categories map correctly for timeline filters', () {
      final baseDate = DateTime.now();
      expect(TaskHistory(id: '1', action: 'created', createdAt: baseDate).actionCategory, equals('creation'));
      expect(TaskHistory(id: '2', action: 'created_from_template', createdAt: baseDate).actionCategory, equals('creation'));
      expect(TaskHistory(id: '3', action: 'status_changed', createdAt: baseDate).actionCategory, equals('status'));
      expect(TaskHistory(id: '4', action: 'completed', createdAt: baseDate).actionCategory, equals('status'));
      expect(TaskHistory(id: '5', action: 'priority_changed', createdAt: baseDate).actionCategory, equals('priority'));
      expect(TaskHistory(id: '6', action: 'reassigned', createdAt: baseDate).actionCategory, equals('assignment'));
      expect(TaskHistory(id: '7', action: 'attempt', createdAt: baseDate).actionCategory, equals('attempt'));
      expect(TaskHistory(id: '8', action: 'postponed', createdAt: baseDate).actionCategory, equals('scheduling'));
      expect(TaskHistory(id: '9', action: 'next_action_date_changed', createdAt: baseDate).actionCategory, equals('scheduling'));
    });

    test('TaskHistoryListResponse deserializes paginated payload correctly', () {
      final json = {
        'items': [
          {
            'id': 'h-1',
            'action': 'created',
            'created_at': '2026-09-28T10:00:00Z',
          },
          {
            'id': 'h-2',
            'action': 'completed',
            'created_at': '2026-09-28T11:00:00Z',
          }
        ],
        'total': 2,
        'page': 1,
        'page_size': 20,
      };

      final response = TaskHistoryListResponse.fromJson(json);

      expect(response.total, equals(2));
      expect(response.page, equals(1));
      expect(response.pageSize, equals(20));
      expect(response.items.length, equals(2));
      expect(response.items[0].action, equals('created'));
      expect(response.items[1].action, equals('completed'));
    });
  });
}
